### ISSUE TITLE
Add Redirects: .wiki and /wiki

### ISSUE THREAD

**Issue by gitr0n1n** [ethereumclassic/ethereumclassic.github.io#322]
https://wiki.ethereumclassic.org link to https://github.com/ethereumclassic/wiki

Create a repo similar to https://github.com/ethereum/wiki

Fill out the Wiki section similar to: https://github.com/ethereum/wiki/wiki

**Comment by gitr0n1n** [comment]
https://github.com/ethereumclassic/wiki/wiki has been created.

To do: create redirects.

https://wiki.ethereumclassic.org/
https://ethereumclassic.org/wiki

When properly linked. Can close this issue.

**Comment by hitchcott** [comment]
I can do the https://ethereumclassic.org/wiki redirect from my side but will need help with the subdomain redirect. Will page relevant people.

@gitr0n1n Do you have an idea of a rule of thumb to determine what ends up in the Wiki and what ends up on the main website?

It will be relatively straightforward to import all of the wiki stuff into the main site.

**Comment by gitr0n1n** [comment]
I'm going to model the wiki after the ethereum wiki since there is so much cross over and someone did a ton of work there. Obviously we will branch off, but this is just trying to get the project up into 2020.

**Comment by gitr0n1n** [comment]
Similar: https://github.com/ethereumclassic/ethereumclassic.github.io/issues/261

**Comment by hitchcott** [comment]
The redirect is now set up for the `/wiki` urls:

https://restructure--ethereumclassic.netlify.com/wiki

The subdomain `wiki.`, however, requires further config by DNS provider -- as it is out of the scope of this repo, can we close this?

**Comment by TheEnthusiasticAs** [comment]
This issue should stay opened as a reminder till the last part is resolved - DNS ...

**Comment by hitchcott** [comment]
Understand that it's not resolved, but I don't think we should keep issues open for things that aren't solvable in the context of this repository.

Perhaps there should be another project that tracks these sorts of admin issues?

**Comment by TheEnthusiasticAs** [comment]
I am fine, if there is another way to track it. Is there another @YazzyYaz ? Sry, if I tagged the wrong person )
